"""
My Bibi — Vault service
Manages the markdown file vault. The vault is:
  vault/
  ├── db.sqlite          (database — managed by SQLite)
  ├── chat/              (reserved for future chat exports)
  ├── media/             (uploaded photos and voice notes)
  ├── memories/          (one .md file per memory, YYYY-MM/ subfolders)
  ├── journal/           (per-user journal, journal/{user_id}/ subfolders)
  └── bloom/             (daily bloom archive)

The vault is Obsidian-compatible — you can open it in Obsidian for a
beautiful read-only view without the app.
"""

import logging
import os
from datetime import datetime, timezone

import aiofiles
import aiofiles.os

logger = logging.getLogger(__name__)

VAULT_SUBDIRS = ["chat", "media", "memories", "journal", "bloom"]


async def init_vault(vault_path: str) -> None:
    """
    Create the vault directory structure if it doesn't exist.
    Called once on application startup.
    """
    os.makedirs(vault_path, exist_ok=True)
    for subdir in VAULT_SUBDIRS:
        os.makedirs(os.path.join(vault_path, subdir), exist_ok=True)

    # Create a vault README so Obsidian shows a nice landing page
    readme_path = os.path.join(vault_path, "README.md")
    if not os.path.exists(readme_path):
        readme_content = """# My Bibi Vault

This folder contains your memories, journal entries, and media files.
It is generated by [My Bibi](https://github.com/yourusername/my-bibi-app).

## Structure

- `memories/` — Shared memories, one markdown file per memory
- `journal/` — Private journal entries per user
- `bloom/` — Daily Bloom prompt archive
- `media/` — Photos and voice notes
- `db.sqlite` — App database (do not edit manually)

## Privacy

Journal entries are private by default. Only the author can read them in the app.
In Phase 4, journal entries will be encrypted at rest.

## Backup

To back up everything: `tar -czf bibi-backup-$(date +%Y%m%d).tar.gz .`
"""
        async with aiofiles.open(readme_path, "w") as f:
            await f.write(readme_content)

    logger.info(f"Vault ready at: {vault_path}")


async def save_memory_as_markdown(
    vault_path: str,
    memory_id: str,
    title: str,
    content: str,
    memory_date: str,
    created_by_name: str,
) -> str:
    """
    Save a memory as a markdown file in vault/memories/YYYY-MM/.
    Returns the relative path of the saved file.
    """
    # Create month subfolder
    year_month = memory_date[:7]  # YYYY-MM
    month_dir = os.path.join(vault_path, "memories", year_month)
    os.makedirs(month_dir, exist_ok=True)

    # Sanitise title for filename
    safe_title = "".join(
        c if c.isalnum() or c in " -_" else "" for c in title
    ).strip()[:50]
    filename = f"{memory_date}-{safe_title or memory_id[:8]}.md"
    filepath = os.path.join(month_dir, filename)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    md_content = f"""---
id: {memory_id}
date: {memory_date}
saved_by: {created_by_name}
saved_at: {now}
---

# {title}

{content or ''}
"""

    async with aiofiles.open(filepath, "w", encoding="utf-8") as f:
        await f.write(md_content)

    logger.info(f"Memory saved to vault: {filepath}")
    return os.path.relpath(filepath, vault_path)


async def save_journal_entry(
    vault_path: str,
    user_id: str,
    entry_id: str,
    title: str | None,
    content: str,
    created_at: str,
    encrypted: bool = False,
) -> str:
    """
    Save a journal entry as a markdown file in vault/journal/{user_id}/.
    Returns the relative path of the saved file.

    Phase 4: `content` arrives as ciphertext (enc:v1:…) and is written
    as-is with `encrypted: true` frontmatter. The vault never holds the
    plaintext of a private entry — the server owner cannot casually read it.
    """
    user_dir = os.path.join(vault_path, "journal", user_id)
    os.makedirs(user_dir, exist_ok=True)

    date_str = created_at[:10]  # YYYY-MM-DD
    safe_title = ""
    if title:
        safe_title = (
            "-"
            + "".join(c if c.isalnum() or c in " -_" else "" for c in title)
            .strip()[:40]
        )
    filename = f"{date_str}{safe_title or '-' + entry_id[:8]}.md"
    filepath = os.path.join(user_dir, filename)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    body = content if not encrypted else (
        "> This entry is encrypted with a key derived from its author's password.\n"
        "> Only the author can read it inside the app.\n\n"
        "```\n" + content + "\n```"
    )
    md_content = f"""---
id: {entry_id}
created_at: {created_at}
updated_at: {now}
private: true
encrypted: {str(encrypted).lower()}
---

{f"# {title}" + chr(10) + chr(10) if title else ""}{body}
"""

    async with aiofiles.open(filepath, "w", encoding="utf-8") as f:
        await f.write(md_content)

    return os.path.relpath(filepath, vault_path)


async def delete_journal_file(vault_path: str, user_id: str, entry_id: str) -> None:
    """
    Delete a journal markdown file. Searches user's journal dir by entry_id
    in the frontmatter.
    """
    user_dir = os.path.join(vault_path, "journal", user_id)
    if not os.path.exists(user_dir):
        return

    for filename in os.listdir(user_dir):
        if not filename.endswith(".md"):
            continue
        filepath = os.path.join(user_dir, filename)
        try:
            async with aiofiles.open(filepath, "r", encoding="utf-8") as f:
                content = await f.read()
            if f"id: {entry_id}" in content:
                await aiofiles.os.remove(filepath)
                logger.info(f"Deleted journal file: {filepath}")
                return
        except Exception as e:
            logger.warning(f"Error reading journal file {filepath}: {e}")


async def save_bloom_to_archive(
    vault_path: str,
    prompt_date: str,
    prompt_text: str,
    answers: list[dict],
) -> None:
    """
    Archive a completed bloom day to vault/bloom/YYYY-MM.md.
    Both answers are written together — the archive is a shared record.
    """
    year_month = prompt_date[:7]
    archive_path = os.path.join(vault_path, "bloom", f"{year_month}.md")

    # Append to monthly archive
    entry = f"""
## {prompt_date}

**{prompt_text}**

"""
    for ans in answers:
        entry += f"**{ans['name']}:** {ans['answer']}\n\n"
    entry += "---\n"

    async with aiofiles.open(archive_path, "a", encoding="utf-8") as f:
        await f.write(entry)
